services:

  api:
    container_name: blobpulse-api
    build:
      context: ./blobpulse-api
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    environment:
      ASPNETCORE_ENVIRONMENT: Production

    volumes:
      - ~/.aspnet/https:/https:ro

    restart: unless-stopped


  ui:
    container_name: blobpulse-ui
    build:
      context: ./blobpulse-ui
      dockerfile: Dockerfile

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: http://api

    depends_on:
      - api